# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Feb 15 17:59:53 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder-One
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.PAss1
    value: !value "xlrelease_PasswordStringVariable_folder_PAss1_value"
- pattern: P1
  stages:
  - stage: New Stage
- template: T1
  scheduledStartDate: 2022-02-15T09:00:00+05:30
  dueDate: 2022-02-15T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Mt
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_T1_scriptUserPassword"
  riskProfile: Default risk profile
- name: Git Trigger
  type: git.Poll
  releaseTitle: Folder-One_1
  template: T1
  releaseFolder: ./
  gitRepository: Local_git
  branch: master
  commitId: 662cc7e11be2e2904aa6dc5c985fe3bd452f2221
