# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Feb 09 13:03:41 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D-23828
spec:
- pattern: Pattern1
  description: Test D-23828
  stages:
  - stage: New Stage
  - stage: New Stage 2
  - stage: New Stage 3
  autoComplete: true
- pattern: Reference_Pattern
  stages:
  - stage: New Stage
  - stage: New Stage (1)
  autoComplete: true
- template: T1
  scheduledStartDate: 2023-02-09T09:00:00+05:30
  dueDate: 2023-02-09T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T
      type: delivery.MarkTrackedItems
      precedingStages: true
      stage: New Stage
      delivery: D-23828/D1
    - name: CD
      type: delivery.CreateDelivery
      ^title: EEEEE
      ^startDate: 2023-02-09T12:51:00+05:30
      ^endDate: 2023-02-10T12:52:00+05:30
      pattern: ./Pattern1
      folder: ./
      variableMapping:
        pythonScript.deliveryId: "${deliveryId}"
    color: '#3d6c9e'
  variables:
  - type: xlrelease.StringVariable
    key: deliveryId
    requiresValue: false
    showOnReleaseStart: false
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_T1_scriptUserPassword"
  riskProfile: Default risk profile
